export default styles = {
    securityPortrait: {
        alignItems: 'center',
        alignSelf: 'center',
        backgroundColor: '#6B4F9E',
        width: '100%',
        zindex: 3,
        justifyContent: 'space-around',
        paddingVertical: 30,
    },
    securityLandscape: {
        alignSelf: 'center',
        alignItems: 'center',
        backgroundColor: '#6B4F9E',
        width: '70%',
        zIndex: 3,
        justifyContent: 'space-around',
        paddingVertical: 30,
    },
    securityButton: {
        height: 55,
        backgroundColor: 'transparent',
        width: '80%',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'white',
        marginBottom: 20,
    },
    buttonText: {
        color: 'white',
        fontSize: 18,
    },
    header: {
        fontSize: 25,
        color: '#4D4D4D',
    },
    confirmText: {
        width: 300,
        fontSize: 20,
        textAlign: 'center',
        color: '#4D4D4D',
    },
    backgroundCover: {
        width: '100%',
        height: '100%',
        zIndex: 10,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 20,
    },
}
