export const FETCH_COTTAGE_BILLINGS = 'FETCH_COTTAGE_BILLINGS'
export const FETCH_COTTAGE_BILLINGS_SUCCESS = 'FETCH_COTTAGE_BILLINGS_SUCCESS'
export const FETCH_COTTAGE_BILLINGS_ERROR = 'FETCH_COTTAGE_BILLINGS_ERROR'

export const FETCH_COMMUNAL_BILLS = 'FETCH_COMMUNAL_BILLS'
export const FETCH_COMMUNAL_BILLS_SUCCESS = 'FETCH_COMMUNAL_BILLS_SUCCESS'
export const FETCH_COMMUNAL_BILLS_ERROR = 'FETCH_COMMUNAL_BILLS_ERROR'

export const TOGGLE_PAYMENT_PAGE_VISIBLE = 'TOGGLE_PAYMENT_PAGE_VISIBLE'

export const CLEAR_BILLINGS_DATA = 'CLEAR_BILLINGS_DATA'

export const SET_CURRENT_COTTAGE_BILLING_ID = 'SET_CURRENT_COTTAGE_BILLING_ID'

export const SET_PAYMENT_DATA = 'SET_PAYMENT_DATA'

export const SET_CURRENT_CARD_ID = 'SET_CURRENT_CARD_ID'

export const SET_TIMER_DATA = 'SET_TIMER_DATA'

export const CLEAR_TIMER = 'CLEAR_TIMER'
