export const SET_UNVOITED_IDEAS = 'SET_UNVOITED_IDEAS'
export const SET_UNOPENED_IDEAS = 'SET_UNOPENED_IDEAS'
export const SET_UNOPENED_NEWS = 'SET_UNOPENED_NEWS'
export const SET_UNPAID_COMMUNAL_BILLS_COUNT = 'SET_UNPAID_COMMUNAL_BILLS_COUNT'
export const CLEAR_COMMON_DATA = 'CLEAR_COMMON_DATA'

export const TOGGLE_SECURITY_TAB_VISIBLE = 'TOGGLE_SECURITY_TAB_VISIBLE'
export const TOGGLE_RULES_PAGE_VISIBLE = 'TOGGLE_RULES_PAGE_VISIBLE'

export const SET_IS_PORTRAIT = 'SET_IS_PORTRAIT'

export const SET_IS_CLIENT_CALL_BACK_SENT = 'SET_IS_CLIENT_CALL_BACK_SENT'

export const TOGGLE_LOADER_VISIBLE = 'TOGGLE_LOADER_VISIBLE'

export const TOGGLE_CONFIRMATION_DIALOG = 'TOGGLE_CONFIRMATION_DIALOG'

export const TOGGLE_SNACKBAR_VISIBLE = 'TOGGLE_SNACKBAR_VISIBLE'

export const SET_NET_INFO_UNSUBSCRIBER = 'SET_NET_INFO_UNSUBSCRIBER'

export const TOGGLE_NEW_CARD_DIALOG = 'TOGGLE_NEW_CARD_DIALOG'

export const TOGGLE_SELECTOR_MODAL_VISIBLE = 'TOGGLE_SELECTOR_MODAL_VISIBLE'
