export const FETCH_IDEA_LIST_DATA = 'FETCH_IDEA_LIST_DATA'
export const FETCH_IDEA_LIST_DATA_SUCCESS = 'FETCH_IDEA_LIST_DATA_SUCCESS'
export const FETCH_IDEA_LIST_DATA_ERROR = 'FETCH_IDEA_LIST_DATA_ERROR'
export const CLEAR_IDEAS_DATA = 'CLEAR_IDEAS_DATA'
export const FETCH_CREATOR_IDEA_LIST_DATA = 'FETCH_CREATOR_IDEA_LIST_DATA'
export const FETCH_CREATOR_IDEA_LIST_DATA_SUCCESS =
    'FETCH_CREATOR_IDEA_LIST_DATA_SUCCESS'
export const FETCH_CREATOR_IDEA_LIST_DATA_ERROR =
    'FETCH_CREATOR_IDEA_LIST_DATA_ERROR'
