export const FETCH_NEWS_LIST_DATA = 'FETCH_NEWS_LIST_DATA'
export const FETCH_NEWS_LIST_DATA_SUCCESS = 'FETCH_NEWS_LIST_DATA_SUCCESS'
export const FETCH_NEWS_LIST_DATA_ERROR = 'FETCH_NEWS_LIST_DATA_ERROR'
export const CLEAR_NEWS_DATA = 'CLEAR_NEWS_DATA'