export const FETCH_PASS_REQUEST_LIST = 'FETCH_PASS_REQUEST_LIST'
export const FETCH_PASS_REQUEST_LIST_SUCCESS = 'FETCH_PASS_REQUEST_LIST_SUCCESS'
export const FETCH_PASS_REQUEST_LIST_ERROR = 'FETCH_PASS_REQUEST_LIST_ERROR'

export const CLEAR_PASS_REQUEST_DATA = 'CLEAR_PASS_REQUEST_DATA'

export const SET_PASS_REQUEST_TYPE = 'SET_PASS_REQUEST_TYPE'
