export const FETCH_CURRENT_CLIENT = 'FETCH_CURRENT_CLIENT'
export const FETCH_CURRENT_CLIENT_SUCCESS = 'FETCH_CURRENT_CLIENT_SUCCESS'
export const FETCH_CURRENT_CLIENT_ERROR = 'FETCH_CURRENT_CLIENT_ERROR'

export const FETCH_CURRENT_RESIDENT = 'FETCH_CURRENT_RESIDENT'
export const FETCH_CURRENT_RESIDENT_SUCCESS = 'FETCH_CURRENT_RESIDENT_SUCCESS'
export const FETCH_CURRENT_RESIDENT_ERROR = 'FETCH_CURRENT_RESIDENT_ERROR'

export const FETCH_COTTAGE_RESIDENTS = 'FETCH_COTTAGE_RESIDENTS'
export const FETCH_COTTAGE_RESIDENTS_SUCCESS = 'FETCH_COTTAGE_RESIDENTS_SUCCESS'
export const FETCH_COTTAGE_RESIDENTS_ERROR = 'FETCH_COTTAGE_RESIDENTS_ERROR'

export const SET_QUESTIONNAIRES_NAVIGATOR = 'SET_QUESTIONNAIRES_NAVIGATOR'

export const CLEAR_PROFILE_DATA = 'CLEAR_PROFILE_DATA'
