export default styles = {
    backdropStyleWithoutAnimation: {
        position: 'absolute',
        height: '100%',
        width: '100%',
        backgroundColor: 'rgba(0,0,0,0.7)',
    },
    cardPortrait: {
        position: 'absolute',
        alignSelf: 'center',
        height: '45%',
        width: '90%',
        backgroundColor: 'white',
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: '40%',
    },
    cardLandscape: {
        marginTop: '5%',
        position: 'absolute',
        alignSelf: 'center',
        height: '70%',
        width: '70%',
        backgroundColor: 'white',
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
    },
    cardMask: {
        color: 'white',
        fontWeight: 'bold',
        fontSize: 20,
    },
    cardLogo: {
        width: 50,
        height: 50,
    },
    cardLogosContainer: {
        position: 'absolute',
        flexDirection: 'row',
        top: 1,
    },
    input: {
        marginTop: '30%',
        width: 300,
        height: 50,
        padding: 10,
        borderWidth: 1,
        borderRadius: 10,
        color: 'black',
        borderColor: 'black',
        fontSize: 15,
    },
    inputLandscape: {
        marginTop: '20%',
        width: 300,
        height: 50,
        padding: 10,
        borderWidth: 1,
        borderRadius: 10,
        color: 'black',
        borderColor: 'black',
        fontSize: 15,
    },
    inputExpDate: {
        borderBottomWidth: 1,
        color: 'black',
        fontSize: 15,
        margin: 10,
        padding: 5,
    },
    expDate: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    button: {
        height: 40,
        backgroundColor: '#939393',
        width: '50%',
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 20,
        alignSelf: 'center',
    },
    disableButton: {
        height: 40,
        backgroundColor: '#c4c4c4',
        width: '50%',
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 20,
        alignSelf: 'center',
    },
    buttonText: {
        color: 'white',
        fontWeight: 'bold',
        fontSize: 15,
    },
}
